### ISSUE TITLE
API

### ISSUE THREAD

**Issue by wiktorvip** [roleoroleo/yi-hack-MStar#153]
Is there any plan in future to add api, to be able manage camera remotely via cmd.

**Comment by roleoroleo** [comment]
For example?

**Comment by wiktorvip** [comment]
for example start/stop RTSP, or any other service. make some configuration like Timezone, so almost everything what is available via page, and some handler to get info about configuration in json format.

**Comment by roleoroleo** [comment]
Timezone web configuration will be in the next release.
No plans for other features at the moment.
But contributions are welcome.

**Comment by roleoroleo** [comment]
You can get also the config files:
http://192.168.1.243:8080/cgi-bin/get_configs.sh?conf=camera
http://192.168.1.243:8080/cgi-bin/get_configs.sh?conf=mqtt
http://192.168.1.243:8080/cgi-bin/get_configs.sh?conf=system
http://192.168.1.243:8080/cgi-bin/get_configs.sh?conf=proxychains

**Comment by wiktorvip** [comment]
yes, this I already discovered.
I was playing little bit with changing parameter but did worked:
example:
`http://IP:8080/cgi-bin/set_configs.sh?conf=camera&led=no`

I had not time to troubleshooting more.

**Comment by roleoroleo** [comment]
set_configs.sh needs a POST with a json file.

**Comment by roleoroleo** [comment]
New wiki:
https://github.com/roleoroleo/yi-hack-MStar/wiki/Web-services-description

**Comment by roleoroleo** [comment]
Do you want to try this?
[service.sh.txt](https://github.com/roleoroleo/yi-hack-MStar/files/4516784/service.sh.txt)

Examples:
http://IP:PORT/cgi-bin/service.sh?name=rtsp&action=start&param1=high
param1 is resolution
http://IP:PORT/cgi-bin/service.sh?name=onvif&action=start&param1=both&param2=yes
param1 is the profile and param2 is watermark
http://IP:PORT/cgi-bin/service.sh?name=mqtt&action=stop
http://IP:PORT/cgi-bin/service.sh?name=ftpd&action=stop&param1=busybox
http://IP:PORT/cgi-bin/service.sh?name=ftpd&action=start&param1=pure-ftpd

**Comment by AirmakZ** [comment]
Hi @roleoroleo,
Incredible job with the customization of this hack firmware! Congratulations for the project.

Taking profit of this post I'd like to ask regarding this feature (Web Services).
All is working according wiki documentation, but I have a doubt.

Is there a way to read current status of Camera Setting?
I'm updating the value "switch_on" properly, but I could not find a way to read this parameter and confirm execution.

I tried a workaround using Configuration parameters, but unfortunately "get_configs.sh?conf=camera" is not updated in real time.

The purpose it to add a switch in Home Assistant like this:

```
  - platform: command_line
    switches:
      camara_garaje:
        command_on: "/usr/bin/curl -X POST http://IP:8080/cgi-bin/camera_settings.sh?switch_on=yes"
        command_off: "/usr/bin/curl -X POST http://IP:8080/cgi-bin/camera_settings.sh?switch_on=no"
        # WORKAROUND IF GET_CONFIGS IS REAL TIME UPDATED
        command_state: "/usr/bin/curl -X GET http://IP:8080/cgi-bin/get_configs.sh?conf=camera"
        value_template: '{{ value_json.SWITCH_ON == "yes" }}'
```

Is there currently a proper way to do it? Of could you include in your task list a Camera Settings Read function if it's able technically?

Thanks a lot!
