### ISSUE TITLE
PTZ and Home Assistant

### ISSUE THREAD

**Issue by ZioTitanok** [roleoroleo/yi-hack-MStar#71]
I'm trying to import my Yi Dome 1080p in Home Assistant.
It was super easy to import the stream, using the ONVIF component.
On the other hand, the Camera doesn't reply on PTZ command request via Home Assistant, while it does via a generic Windows software and, of course, via web interface.

Any suggestion?
Thank you.

**Comment by roleoroleo** [comment]
Unfortunately I don't have a dome cam so I can run only few tests.

Regarding your issue I think there is a problem with ha, I tested it now and doesn't work:
https://github.com/home-assistant/home-assistant/issues/27744
https://github.com/home-assistant/home-assistant/pull/30152

But there is a workaround, if you want.
When I tested the software I did not configure the ptz inside onvif but as a set of switches.
configuration.yaml:
```
  - platform: template
    switches:
      switch_cam_left:
        value_template: "off"
        turn_on:
          service: rest_command.ptz_cam_left
        turn_off:

rest_command :
  ptz_cam_left:
    url: http://192.168.0.200:8080/cgi-bin/webui?command=ptzl
```
And in lovelace:
```
    cards:
      - camera_image: camera.cam
        entities:
          - entity: switch.switch_cam_left
            icon: 'mdi:arrow-left-bold-circle-outline'
        title: MyCam
        type: picture-glance
```
